config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles # In the Blog application, you will
  # now create a new resource. A resource is the term used
  # for a collection of similar objects, such as articles,
  # people or animals. You can create, read, update and
  # destroy items for a resource and these operations are
  # referred to as CRUD operations.

# Rails provides a resources method which can be used to declare a standard
# REST resource. You need to add the article resource to the config/routes.rb
# so the file will look as follows:



  root 'welcome#index' # root 'welcome#index' tells
  # Rails to map requests to the root of the application
  # to the welcome controller's index action and get
  # 'welcome/index' tells Rails to map requests to
  # http://localhost:3000/welcome/index to the welcome
  # controller's index action.
end

# This is your application's routing file which
# holds entries in a special DSL (domain-specific
# language) that tells Rails how to connect
# incoming requests to controllers and actions.
# Edit this file by adding the line of code root
# 'welcome#index'.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                  length: { minimum: 5 }
end





#  Article class inherits from ApplicationRecord. ApplicationRecord inherits from
#  ActiveRecord::Base which supplies a great deal of functionality to your Rails
#  models for free, including basic database CRUD (Create, Read, Update, Destroy)
#  operations, data validation, as well as sophisticated search support and the
#  ability to relate multiple models to one another.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

# In this case, it's the articles/new template. Rails will
# first look for this template. If not found, then it will
# attempt to load a template called application/new. It looks
# for one here because the ArticlesController inherits from 
# ApplicationController.

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController  # inherits from application controller
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id]) # A couple of things to note. We use Article.find
    # to find the article we're interested in, passing in params[:id] to get the :id parameter
    # from the request. We also use an instance variable (prefixed with @) to hold a reference
    # to the article object. We do this because Rails will pass all instance variables to the
    # view.

  end

  def new
    @article = Article.new
    # With the validation now in place, when you call @article.save on an invalid
    # article, it will return false. If you open app/controllers/articles_controller.rb
    # again, you'll notice that we don't check the result of calling @article.save
    # inside the create action. If @article.save fails in this situation, we need
    # to show the form back to the user.
  end

  def create
    @article = Article.new(article_params) # Article.new is capitalized above, whereas most other references to articles in this guide have used lowercase. In this context, we are referring to the class named Article that is defined in app/models/article.rb. Class names in Ruby must begin with a capital letter.

    if @article.save
      redirect_to @article
  #   Here's what's going on: every Rails model can be initialized with its
  #   respective attributes, which are automatically mapped to the respective
  #   database columns. In the first line we do just that (remember that
  #   params[:article] contains the attributes we're interested in). Then,
  #   @article.save is responsible for saving the model in the database.
  #   Finally, we redirect the user to the show action, which we'll define
  #   later.
    else
      render 'new'
#       The new action is now creating a new instance variable called @article,
#       and you'll see why that is in just a few moments.
# Notice that inside the create action we use render instead of redirect_to
#  when save returns false. The render method is used so that the @article object
#     is passed back to the new template when it is rendered. This rendering is
#     done within the same request as the form submission, whereas the redirect_to
#     will tell the browser to issue another request.


    end
   end

   private
   def article_params
     params.require(:article).permit(:title, :text)
   end
end


# create the controller by running $ bin/rails generate controller Articles
# inside class you'll define methods that will become actions for this controller
# These actions will perform CRUD operations on articles within system

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
<!-- form_with = you pass it an identifying scope for this form, in this case it
is the symbol :article, This tells the form_with helper what this form is for.
Inside the block for this method, the FormBuilder object - represented by form -
is used to build two labels and two text fields, one each for the title and text
of an article. Finally, a call to submit on the form object will create a submit
button for the form.-->
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

  <!-- A few things are going on. We check if there are any errors with 
  @article.errors.any?, and in that case we show a list of all errors with
  @article.errors.full_messages.
  pluralize is a rails helper that takes a number and a string as its arguments.
  If the number is greater than one, the string will be automatically pluralized.
  The reason why we added @article = Article.new in the ArticlesController is
  that otherwise @article would be nil in our view, and calling @article.errors.any?
  would throw an error.
  Rails automatically wraps fields that contain an error with a div with class
  field_with_errors. You can define a css rule to make them standout. -->
<% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  ...
<% end %>

<%= link_to 'Back', articles_path %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>


<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

<!-- link to the app/views/articles/show.html.erb template to go back to the
 index action as well, so that people who are viewing a single article can
 go back and view the whole list again -->

 <!-- If you want to link to an action in the same controller, you don't need
 to specify the :controller option, as Rails will use the current controller
 by default.

 In development mode (which is what you're working in by default), Rails
 reloads your application with every browser request, so there's no need
 to stop and restart the web server when a change is made. -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>

<!-- The link_to method is one of Rails' built-in view helpers. It creates a
hyperlink based on text to display and where to go - in this case, to the
path for articles. -->